### ISSUE TITLE
Build uses wrong version of CLI

### ISSUE THREAD

**Issue by EO3-Kopf** [dspace-group/dscom#139]
If I set `PlatformTarget` to `x86` the CLI version ist used for creating the tlb-file. So far so good. However the wrong version is used. The build task returns an error, which points out that the x64-version ist used.

> Fehler	MSB3073	Der Befehl "D:\Entwicklung\.nuget\packages\dspace.runtime.interopservices.buildtasks\0.21.0\build\..\tools\x64\dscom.exe       tlbexport    D:\Entwicklung\<PathTo>\My.dll  --out D:\Entwicklung\<PathTo>\My.tlb" wurde mit dem Code 1 beendet.	

According to the message the error originates in `dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets`, line 62. However I think it originates in the lines 23 resp. 24. In Line 23 `_DsComToolsFileDir` is set without condition. Line 24 provides condition for x86. To me it seems the condition ist wrong. If I comment out line 23 `$(_DsComToolsFileDir)` becomes empty (instead of pointing to `$(MsBuildThisFileDirectory)..\tools\x86\`). Therefore I think something with the condition in line 24 is wrong.

**Comment by EO3-Kopf** [comment]
I added a new line with a different condition:
`<_DsComToolsFileDir Condition="'$(PlatformTarget)' == 'x86'">$(MsBuildThisFileDirectory)..\tools\x86\</_DsComToolsFileDir>`
This one works.

**Comment by carstencodes** [comment]
I've actually overseen this and it might be intentional, as the value is automatically set if the `Platform` is set accordingly (cf. [this](https://github.com/dotnet/sdk/blob/c3df740b1469a0aa2fce4ff95c10151d5b60d128/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L76) ). 

Nevertheless, I just stumbled across the [VS Documentation](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2022), where it is actually set.

What's the actual value of `Platform` in your csproj?

**Comment by EO3-Kopf** [comment]
`Platform` is `Any CPU`.

**Comment by carstencodes** [comment]
Yeah, ok, than it might not be set automatically properly. The issue should be fixed

**Comment by marklechtermann** [comment]
Fixed with #146
