### ISSUE TITLE
warning TX00000000

### ISSUE THREAD

**Issue by ulued** [dspace-group/dscom#179]
I'm getting this error after a .Net 6 port. TlbExport (.Net 4.7.2) could generate the files, dscom reports this error on IEnumerable
dscom : warning TX00000000 : ComVisible interface System.Collections.IEnumerable could not be added to source type ....

The c# dll compiles without errors.

**Comment by SOsterbrink** [comment]
The problem is, that while `IEnumerable `is declared as `ComVisible`, Microsoft does not provide a TLB for this. And we can't generate the TLB by ourselves. 
The same problem exists with every other class and interface that's declared as `ComVisible `from .NETFrameworkAssemblies  

Which sadly leads to the problem you described. 
See #87 
This is currently a limitation and we don't know a way to solve it.

**Comment by ulued** [comment]
Thanks Sebastian for taking the time to comment the issue
