### ISSUE TITLE
Mixed assembly support

### ISSUE THREAD

**Issue by gureedo** [dspace-group/dscom#207]
Hi!

Is it possible to return mixed assembly support?
Latest version is unable to perform tlbexport for mixed assembly or assembly with mixed assembly dependency.
I have digged a bit and found that AssemblyLoadContext is constructed with unload feature which is not supported for mixed assemblies.

**Comment by SOsterbrink** [comment]
Hi @gureedo , 

what kind of mixed assemblies are you talking about? 32-bit and 64-bit assemblies? Different .NET versions? C# and c++ ? 
64-bit assemblies which call COM interfaces of 32-bit assemblies or the other way around?  

Can you provide an example for what you want to do?

**Comment by gureedo** [comment]
Hi!
This one https://learn.microsoft.com/en-us/cpp/dotnet/mixed-native-and-managed-assemblies?view=msvc-170

**Comment by SOsterbrink** [comment]
Which version worked and is it only the newest version which is affected?  

I'll have to take a closer look how the previous fix or the dependency updates introduced the problem.

**Comment by gureedo** [comment]
Current behavior was introduced in #192 
And I have found why it isn't allowed to unload mixed assemblies https://github.com/dotnet/coreclr/pull/23430

**Comment by SOsterbrink** [comment]
Thank you, that's very helpful. I'll take a closer look what I can do about it and talk to @mlessmann who wrote the relevant change. The problem which motivated the change is sadly not documented here in GitHub. 

But it's likely that this will take some days to resolve.

**Comment by marklechtermann** [comment]
@SOsterbrink 

Maybe we could check in the Dispose method whether it is a mixed assembly.
In this case, we could ignore to call OnLoad method.

Mybe with...
[https://learn.microsoft.com/en-us/dotnet/api/system.reflection.module.getpekind?view=net-7.0](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.module.getpekind?view=net-7.0)

`Module.GetPEKind(PortableExecutableKinds, ImageFileMachine)`

stack overflow to the rescue...
[https://stackoverflow.com/a/17626536/8690889](https://stackoverflow.com/a/17626536/8690889)

Unfortunately, I'm not really familiar with mixed assemblies.

**Comment by SOsterbrink** [comment]
After further study of the problem: Your idea will not work @marklechtermann  because to use `Module.GetPEKind` we would have to load the assembly to determine it's PEKind. In the example and the documentation I don't see a way to use it without first loading the individual assembly. 

Also the `AssemblyLoadContext` we use here is a global thing for the dscom and we would have to determine this information before loading the first assembly into this load context. The information about whether to context allows unloading assemblies needs to be know during the `Creator` call. 

So the only way I see to do it is to select the desired behavior before creating the `AssemblyLoadContext` and the easiest way would be a manually set option.

**Comment by marklechtermann** [comment]
Brief explanation of the patch:

We (@SOsterbrink and @matthiasnissen) discussed this today.
In the case of the command line client, it should not be necessary to unload the assemblies.
Since the process ends after generation anyway.
