### ISSUE TITLE
dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets does not create a target for 32-bit assemblies

### ISSUE THREAD

**Issue by jmorgan-habs** [dspace-group/dscom#247]
I'm trying to use the NuGet package to integrate TLB exports into my build process. For pure 32-bit libraries, it appears that there is a conditional statement here that is blocking a target for the export from being generated, despite lines earlier in the file which appear to be setting up the use of the 32-bit dscom.exe

https://github.com/dspace-group/dscom/blob/f1754d68ff89ff55eabd2eb33d4779a43e2350c7/src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets#L32-L36

**Comment by jmorgan-habs** [comment]
Apologies if I'm misunderstanding something here with regards to the pure 32-bit support. If the dscom library in the x86 folder is meant to only support AnyCPU libraries, can the dscom32 library also be added to the build targets package?

**Comment by carstencodes** [comment]
I'm Not Sure, If I will be able to Look at that tomorrow, but I should be able to Look at that on friday.

Regards 

Carsten

**Comment by carstencodes** [comment]
I had some issues with x86 based builds in the past, maybe That's the reason why IT accidently was Not added.

This is rather Strange. Maybe IT slipped through. 

I'll Try to get it running with some of our Samples.

**Comment by carstencodes** [comment]
Ok, I can confirm that, when I run [the example script](), it skips the x86 builds:

![image](https://github.com/dspace-group/dscom/assets/1760987/e1ce9844-9b07-4b74-bff0-ff0480884c8c)

But runs this in x64

![image](https://github.com/dspace-group/dscom/assets/1760987/5f064be9-2895-4845-99f8-716b387df2b6)

I'll correct that and run some tests with 32 bit based builds

**Comment by carstencodes** [comment]
I found an issue with the github workflow / actions.

On my local machine I have installed .NET 8 x86, but it seems not to be installed on the build machines. 

Even though I am using a self-contained build.

I'll investigate it any further and keep you informed.

**Comment by carstencodes** [comment]
@marklechtermann @SOsterbrink I am using self-contained=false in [DsComPackaging.targets](https://github.com/dspace-group/dscom/blob/55893991b6f487b17c33995db3591dda9367a0ee/src/dscom.build/DsComPackaging.targets#L21). The reason is 

1. It decreases the size of the NuGet packages
2. It does not bundle the runtime which is better for (security) compliance reasons.

I have no idea, how to install the .NET 8 Runtime in 32 bit (x86) on the github runners.

I do two things:

1. I can add dotnet runtime using a self-contained distribution
2. I can disable the compatibility test for x86 during pull requests. 

Both options are not really attractive. And honestly, I am reluctant to do any of this. I am more a fan of removing the root cause.

Do you have any idea, HOW to add the .NET RT 8.0 x86 to the agent?

**Comment by carstencodes** [comment]
According to the [installer script in the action](https://github.com/actions/setup-dotnet/blob/5d1464d5da459f3d7085106d52e499f4dc5d0f59/externals/install-dotnet.ps1#L263) the variable processor architecture could be used, but this is skipped.

**Comment by marklechtermann** [comment]
I would temporarily deactivate the x86 check.
I don't know of any other solution.
If we come up with something better, we can release the x86 test later.
