### ISSUE TITLE
Properties Description

### ISSUE THREAD

**Issue by electro-logic** [dspace-group/dscom#281]
Hello all,

This syntax is working
```
        int MyProperty {
            [Description("MyPropertyDescription")]
            get; set;
        }
```
but this (more handy) syntax is not working
```
        [Description("MyPropertyDescription")]
        int MyProperty { get; set; }
```
and in this last case "helpstring" is not generated for the property.

Is this a bug?

Thank you

**Comment by marklechtermann** [comment]
Hello electro-logic,

the behavior is intentional.
tlbexp behaves in exactly the same way here.

You can check this with this demo:
https://github.com/dspace-group/dscom/tree/main/src/dscom.demo/assembly7

Both tlbexp.exe and dscom.exe do not generate a docString if the DescriptionAttribute is directly at the property.

Beste Grüße, Mark

**Comment by electro-logic** [comment]
Thank you Mark for the quick reply and thanks again for developing this great tool.
