### ISSUE TITLE
File errors when building multiple projects in parallel

### ISSUE THREAD

**Issue by Arakys7** [dspace-group/dscom#310]
**Problem**
I have multiple interdependent C# projects that use dscom to generate tlbs.
For example:
Base and Proj1, Proj2, and Proj3. The latter all depend on Base, but not on each other.

I also use a single output folder: `Build\bin` and a single tlb folder: `Build\tlb`.
The arguments I define that are sent to dscom (in the `DsComExportTypeLibraryAfterBuild` target) are basically:

`dscom.exe tlbexport "Build\bin\Base.dll" --tlbrefpath "Build\tlb" --out "Build\tlb\Base.tlb"`

And this works, as long as I force each project to build sequentially.
However, when I allow MSBuild to build projects simultaneously, I get intermittent file access errors:

`Failed to export type library. Failed to load type library Build\bin\Proj1.tlb. Access is denied (0x80029C4A (TYPE_E_CANTLOADLIBRARY))`

**Investigation**
Initially, MSBuild builds Base.dll, and dscom creates Base.tlb.
Then MSBuild builds Proj1, Proj2, and Proj3 at the same time.

I am using the `tlbrefpath` parameter, so dscom reads and *loads all* the tlbs in that location before creating the tlb.
However, because Proj1, Proj2, and Proj3 are all writing to the same folder, when Proj3 reads the `tlbrefpath` location, it sees Proj1.tlb and then tries to load a file that's currently being written.

The problem file changes, depends on the exact MSBuild timings. With a dozen projects, at least one fails.

**Proposed Solution**
I propose that tlb files in the `tlbrefpath` location are loaded only when needed, instead of at the beginning, loading all that exist there.

**Comment by carstencodes** [comment]
I have seen a similar issue: If you do not use --embed, the assemblies will be loaded into a non-collectible assembly load context, making the handle becoming exclusive, so that only one process may load the assembly.

So, when when loading the assemblies on demand, this _may_ help.

I would rather suggest adding a --support-multiple flag to the cli, that makes the AssemblyLoadContext collectible and ensures that the assembly load context can be removed again and hence the assembly load method does not lock the assembly.

We can pre-define this value from msbuild Property `$(MSBuildNodeCount)`.

What do you think, @SOsterbrink @marklechtermann @matthiasnissen ?
