### ISSUE TITLE
Warning regarding type substitution cannot be avoided by explicitly changing the type with MarshalAs.

### ISSUE THREAD

**Issue by matthiasnissen** [dspace-group/dscom#50]
If an interface is referenced as a parameter that cannot be resolved by a TLB, a warning comes up, see this simple example:
```
public interface WarningTestInterface
{
    System.Collections.IList GetList();
}

dscom : warning TX0013116F : Warning: Type library exporter could not find the type library for IList.  IUnknown was substituted for the interface.
```
If you now want to resolve this warning by an explicit MarshalAs as follows, the warning still appears.
``` 
public interface WarningTestInterface
{
    [return: MarshalAs(UnmanagedType.IUnknown)]
    System.Collections.IList GetList();
}
```
One should be able to avoid the warning by an explicit MarshalAs, since the origin type becomes irrelevant with it.

**Comment by SOsterbrink** [comment]
The solution should be that the warning is not given if the explicit MarshalAs attribute is given.

**Comment by marklechtermann** [comment]
Same problem with `in-parameter`.
In case of `myfunction([MarshalAs(UnmangedType.SafeArray)Array elements)` dscom should create ` VT_SAFEARRAY->VT_VARIANT`
See:  
[https://learn.microsoft.com/en-us/dotnet/framework/interop/default-marshalling-for-array](https://learn.microsoft.com/en-us/dotnet/framework/interop/default-marshalling-for-arrays)

@SOsterbrink

**Comment by marklechtermann** [comment]
The behavior ist correct! In case of  `System.Array` the tlbexp.exe will create a `VT_SAFEARRAY->VT_VARIANT`. The reason for this behavior is not the MarshalAs attribute, because tlbexp.exe uses the `System.Array` type and not the type from the MarshalAs attribute. 
In case of dotnet >=5 the `System.Array`is not COM visible - the interface `System.Collection.IEnumerable` is COM visible.
But Microsoft does not provide any type libraries for interfaces or classes from the BCL.
dscom will create `IUnkown` as type for this use case.
